# Generated by Django 4.1.5 on 2023-01-29 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="image",
            field=models.ImageField(upload_to="", verbose_name="Изображение"),
        ),
    ]
