# Generated by Django 4.1.5 on 2023-01-18 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0005_rename_img_recipe_image_recipeingredients_amount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="image",
            field=models.ImageField(
                upload_to="media/django/%Y/%m/%d/", verbose_name="Изображение"
            ),
        ),
    ]
