# Generated by Django 4.1.5 on 2023-01-18 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0006_alter_recipe_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="image",
            field=models.ImageField(
                upload_to="media/django/temp/", verbose_name="Изображение"
            ),
        ),
    ]
