# Generated by Django 4.1.5 on 2023-01-17 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ingredients", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="ingredient",
            old_name="unit",
            new_name="measurement_unit",
        ),
    ]
