version: '3.3'

services:

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    volumes:
      - ../frontend/:/app/result_build/

  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_value:/var/lib/postgresql/data/
    depends_on:
      - frontend
    env_file:
      - ./.env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s

  web:
    build:
      context: ../foodgram
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - ../foodgram/:/backend/
      - media_value:/backend/media/django/
      - static_value:/backend/static/django/
    depends_on:
      - db
    env_file:
      - ./.env
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://127.0.0.1:8000/admin"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s

  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../foodgram:/usr/share/nginx/html/backend/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - media_value:/var/html/media/django/
      - static_value:/var/html/static/django/
    depends_on:
      - web
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://127.0.0.1/"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  media_value:
  static_value:
  postgres_value:
