# Generated by Django 4.1.5 on 2023-02-05 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="subscription",
            name="subscriber_author",
        ),
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(max_length=150, verbose_name="Пароль"),
        ),
        migrations.AddConstraint(
            model_name="subscription",
            constraint=models.UniqueConstraint(
                fields=("subscriber", "author"), name="uniqe_subscriber-author"
            ),
        ),
        migrations.AddConstraint(
            model_name="subscription",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("author__gt", models.F("subscriber")),
                    ("author__lt", models.F("subscriber")),
                    _connector="OR",
                ),
                name="subscriber_not_author",
            ),
        ),
    ]
